### ISSUE TITLE
expand permittivity to full anisotropic real tensor

### ISSUE THREAD

**Issue by oskooi** [stevengj/meep#619] opened 2018-11-23 23:46 UTC
Currently, ε is restricted to a real, symmetric tensor via the `epsilon_diag` and `epsilon_offdiag` properties of the [`Medium`](https://meep.readthedocs.io/en/latest/Python_User_Interface/#medium) object. It would be useful to expand this to a full anisotropic, real tensor. This would enable the modeling of a number of [liquid crystals](https://en.wikipedia.org/wiki/Liquid_crystal) used for display applications.

**Comment by stevengj** [comment] 2018-11-24 00:33
Do you mean nonreciprocal materials?  Lossless nonreciprocal materials require a complex (Hermitian) ε tensor, and lossy ones require dispersion, so both of these would be need to be in the susceptibility or conductivity framework and not in the context of our dispersionless ε and μ properties, so `epsilon_diag` and `epsilon_offdiag` seem not really relevant to nonreciprocal media.

**Comment by stevengj** [comment] 2018-11-24 00:34
Closing as nonreciprocal materials are a duplicate of #60.

**Closed by stevengj** 2018-11-24 00:34 UTC
